### ISSUE TITLE
无法转换 raw.csv 到 vector.csv

### ISSUE THREAD

**Issue by kris2025** [ConnectAI-E/Feishu-Vector-Knowledge-Management#13]
go run ./cmd - prepare import -f ./data/demo/vector.csv
![image](https://github.com/ConnectAI-E/Feishu-Vector-Knowledge-Management/assets/134351431/ee064c61-ccb4-4148-8cd5-784fbdfb48cf)

[ec2-user@ip-10-10-200-10 Feishu-Vector-Knowledge-Management]$ go run ./cmd - prepare import -f ./data/demo/vector.csv
2023/06/21 07:29:00 /home/ec2-user/Feishu-Vector-Knowledge-Management/pkg/qdrantkit/collection.go:69: Get "http://qdrant:6333/collections/lark-vkm": dial tcp: lookup qdrant on 10.10.0.2:53: no such host
2023/06/21 07:29:00 /home/ec2-user/Feishu-Vector-Knowledge-Management/pkg/qdrantkit/collection.go:49: Put "http://qdrant:6333/collections/lark-vkm": dial tcp: lookup qdrant on 10.10.0.2:53: no such host
panic: init error:Put "http://qdrant:6333/collections/lark-vkm": dial tcp: lookup qdrant on 10.10.0.2:53: no such host

goroutine 1 [running]:
lark-vkm/pkg/qdrantkit.Qdrant.init({{0xc00026ea68?, 0xbe69ee?}, {0xc0003d80f8?, 0xdb00ad4000000000?}})
	/home/ec2-user/Feishu-Vector-Knowledge-Management/pkg/qdrantkit/collection.go:33 +0xcb
lark-vkm/pkg/qdrantkit.New(...)
	/home/ec2-user/Feishu-Vector-Knowledge-Management/pkg/qdrantkit/qdrant.go:13
lark-vkm/cmd/prepare.glob..func3(0x11567e0?, {0xc0003d0060?, 0x3?, 0x3?})
	/home/ec2-user/Feishu-Vector-Knowledge-Management/cmd/prepare/import.go:36 +0xfb
github.com/spf13/cobra.(*Command).execute(0x11567e0, {0xc0003d0000, 0x3, 0x3})
	/home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000332c00)
	/home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/ec2-user/Feishu-Vector-Knowledge-Management/cmd/lark-vkm.go:21 +0x15d
exit status 2
[ec2-user@ip-10-10-200-10 Feishu-Vector-Knowledge-Management]$

**Comment by kris2025** [comment]
restart docker ps
